# Generated by Django 4.2.13 on 2024-12-16 09:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text comment')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 16, 12, 45, 49, 887470), verbose_name='Data comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blog', verbose_name='Comment Article')),
            ],
            options={
                'verbose_name': 'Comment Article blog',
                'verbose_name_plural': 'Comment and Article blog',
                'db_table': 'Comment',
                'ordering': ['-date'],
            },
        ),
    ]
