# Generated by Django 4.2.13 on 2024-12-16 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 16, 12, 57, 37, 99382), verbose_name='Data comment'),
        ),
    ]
