# Generated by Django 4.2.13 on 2024-12-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_comment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
